=== tbrk/treeplate/xsltsrc/sitetree.dtd
<!ENTITY % itemdata "prefix?, suffix?, author?, style?, icon?, link*, keyword*">

<!ELEMENT sitetree        (%itemdata;, rooturl, item*)>
<!ELEMENT rooturl         (#PCDATA)>
<!ELEMENT item            (%itemdata;, name, file, item*)>
<!ATTLIST item directory  CDATA #IMPLIED>
<!ATTLIST item inmenu     CDATA "yes">
<!ATTLIST item homelink   CDATA #IMPLIED>
<!ATTLIST item sitemap    CDATA "yes">
<!ATTLIST item changefreq (always|hourly|daily|weekly|
			   monthly|yearly|never) "monthly">
<!ATTLIST item priority   CDATA "0.5">
<!ELEMENT prefix          (#PCDATA)>
<!ELEMENT suffix          (#PCDATA)>
<!ELEMENT author          (#PCDATA)>
<!ATTLIST author href     CDATA #REQUIRED>
<!ELEMENT style           (#PCDATA)>
<!ELEMENT icon            (#PCDATA)>
<!ELEMENT name            (#PCDATA)>
<!ELEMENT file            (#PCDATA)>
<!ELEMENT description     (#PCDATA)>

<!ELEMENT link		  (#PCDATA)>
<!ATTLIST link rel	  CDATA #REQUIRED>

<!ELEMENT keyword	  (#PCDATA)>
<!ATTLIST keyword inherit CDATA "yes">

=== tbrk/treeplate/src/sitetree.xml
<!DOCTYPE sitetree SYSTEM "sitetree.dtd">
<sitetree>

<rooturl>http://www.yoursite.com</rooturl>

<prefix>Treeplate - </prefix>
<suffix> (test)</suffix>
<author href="mailto:me@mysite.com">John Doe</author>
<style>basic.css</style>

<item homelink="yes" priority="1.0">

    <name>Home</name>
    <file>index</file>

    <item directory="subdir">
	<name>Test</name>
	<file>test</file>
    </item>
</item>

<item>
    <name>Treeplate</name>
    <file>treeplate</file>

    <author href="mailto:tbourke@cse.unsw.edu.au">Timothy Bourke</author>
    <keyword>xml</keyword>
</item>

</sitetree>
